using System.Windows.Media;

namespace Musicefy.Core.Theme
{
    /// <summary>
    /// The heart of the Aniyomi approach: each <see cref="AppTheme"/> entry provides
    /// exactly two hand-crafted <see cref="MusicefyColorScheme"/> instances. No HCT
    /// math — every hex value is authored directly. The final active ColorScheme is
    /// resolved by a single expression:
    /// <code>AppThemeColorSchemes.GetColorScheme(appTheme, themeMode)</code>
    /// </summary>
    public static class AppThemeColorSchemes
    {
        // ── Public resolution API ────────────────────────────────────────────

        /// <summary>
        /// Returns the active <see cref="MusicefyColorScheme"/> for the given
        /// AppTheme + ThemeMode combination. AMOLED mode takes the dark scheme's
        /// accent colors but replaces all surface/background slots with pure black.
        /// </summary>
        public static MusicefyColorScheme GetColorScheme(AppTheme theme, ThemeMode mode, bool? systemIsDark = null)
        {
            bool isDark = ResolveDark(mode, systemIsDark);
            var (light, dark) = GetPair(theme);
            var scheme = isDark ? dark : light;

            // AMOLED: take the dark scheme's accents but zero-out all surfaces
            if (mode == ThemeMode.Amoled)
                scheme = ApplyAmoled(scheme);

            return scheme;
        }

        /// <summary>
        /// Returns the four swatch colors used in the palette picker preview card.
        /// Always samples from the light scheme regardless of the user's current mode,
        /// just like Aniyomi's picker.
        /// </summary>
        public static (Color primary, Color surface, Color secondary, Color tertiary)
            GetPreviewColors(AppTheme theme)
        {
            var (light, _) = GetPair(theme);
            return (light.Primary, light.Surface, light.Secondary, light.Tertiary);
        }

        // ── Dark mode resolution ─────────────────────────────────────────────

        private static bool ResolveDark(ThemeMode mode, bool? systemIsDark) => mode switch
        {
            ThemeMode.Light  => false,
            ThemeMode.Dark   => true,
            ThemeMode.Amoled => true,
            _                => systemIsDark ?? false,   // System
        };

        // ── Palette lookup ───────────────────────────────────────────────────

        private static (MusicefyColorScheme Light, MusicefyColorScheme Dark) GetPair(AppTheme theme)
            => theme switch
            {
                AppTheme.GreenApple          => (GreenAppleLight, GreenAppleDark),
                AppTheme.Lavender            => (LavenderLight, LavenderDark),
                AppTheme.StrawberryDaiquiri  => (StrawberryDaiquiriLight, StrawberryDaiquiriDark),
                AppTheme.MidnightDusk        => (MidnightDuskLight, MidnightDuskDark),
                AppTheme.Tako                => (TakoLight, TakoDark),
                AppTheme.TealTurquoise       => (TealTurquoiseLight, TealTurquoiseDark),
                AppTheme.TidalWave           => (TidalWaveLight, TidalWaveDark),
                AppTheme.CottonCandy         => (CottonCandyLight, CottonCandyDark),
                AppTheme.Cloudflare          => (CloudflareLight, CloudflareDark),
                AppTheme.Doom                => (DoomLight, DoomDark),
                AppTheme.Mocha               => (MochaLight, MochaDark),
                AppTheme.Sapphire            => (SapphireLight, SapphireDark),
                AppTheme.Nord                => (NordLight, NordDark),
                AppTheme.YinAndYang          => (YinAndYangLight, YinAndYangDark),
                AppTheme.Yotsuba             => (YotsubaLight, YotsubaDark),
                AppTheme.Monochrome          => (MonochromeLight, MonochromeDark),
                // Default + Dynamic both fall back to Default palette.
                // Dynamic is handled specially by ThemeManager using HCT extraction.
                _ => (DefaultLight, DefaultDark),
            };

        // ── AMOLED override ──────────────────────────────────────────────────

        /// <summary>
        /// Keep all accent/content colors, replace every surface slot with near-black.
        /// </summary>
        private static MusicefyColorScheme ApplyAmoled(MusicefyColorScheme dark) => new()
        {
            // Preserve accent colors
            Primary                 = dark.Primary,
            OnPrimary               = dark.OnPrimary,
            PrimaryContainer        = dark.PrimaryContainer,
            OnPrimaryContainer      = dark.OnPrimaryContainer,
            Secondary               = dark.Secondary,
            OnSecondary             = dark.OnSecondary,
            SecondaryContainer      = dark.SecondaryContainer,
            OnSecondaryContainer    = dark.OnSecondaryContainer,
            Tertiary                = dark.Tertiary,
            OnTertiary              = dark.OnTertiary,
            TertiaryContainer       = dark.TertiaryContainer,
            OnTertiaryContainer     = dark.OnTertiaryContainer,
            Error                   = dark.Error,
            OnError                 = dark.OnError,
            ErrorContainer          = dark.ErrorContainer,
            OnErrorContainer        = dark.OnErrorContainer,
            Outline                 = dark.Outline,
            OutlineVariant          = dark.OutlineVariant,
            InverseSurface          = dark.InverseSurface,
            InverseOnSurface        = dark.InverseOnSurface,
            InversePrimary          = dark.InversePrimary,
            // Override surfaces to near-black
            Surface                 = C(0xFF000000),
            SurfaceContainerLowest  = C(0xFF000000),
            SurfaceContainerLow     = C(0xFF050505),
            SurfaceContainer        = C(0xFF0A0A0A),
            SurfaceContainerHigh    = C(0xFF0F0F0F),
            SurfaceContainerHighest = C(0xFF141414),
            SurfaceVariant          = dark.SurfaceVariant,
            OnSurface               = dark.OnSurface,
            OnSurfaceVariant        = dark.OnSurfaceVariant,
            IsDark                  = true,
        };

        // ── Helper ───────────────────────────────────────────────────────────

        private static Color C(uint argb) => Color.FromArgb(
            (byte)(argb >> 24), (byte)(argb >> 16), (byte)(argb >> 8), (byte)argb);

        // ══════════════════════════════════════════════════════════════════════
        // Palette Definitions
        // Each AppTheme has two static MusicefyColorScheme objects with
        // hand-authored hex values matching the Aniyomi/Mihon theme colours.
        // ══════════════════════════════════════════════════════════════════════

        // ── Default (Musicefy's warm coral-red identity) ─────────────────────

        private static readonly MusicefyColorScheme DefaultLight = new()
        {
            IsDark = false,
            Primary             = C(0xFFB5261E),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFFFDAD4),
            OnPrimaryContainer  = C(0xFF410001),
            Secondary           = C(0xFF775651),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFFFDAD4),
            OnSecondaryContainer= C(0xFF2C1512),
            Tertiary            = C(0xFF705C2E),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFFCDFA6),
            OnTertiaryContainer = C(0xFF261A00),
            Error               = C(0xFFB3261E),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFF9DEDC),
            OnErrorContainer    = C(0xFF410E0B),
            Surface             = C(0xFFFFFBFE),
            OnSurface           = C(0xFF1C1B1F),
            SurfaceVariant      = C(0xFFF4F0F0),
            OnSurfaceVariant    = C(0xFF49454F),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFF9F7F9),
            SurfaceContainer        = C(0xFFF4F2F5),
            SurfaceContainerHigh    = C(0xFFECEAEF),
            SurfaceContainerHighest = C(0xFFE6E1E5),
            Outline             = C(0xFF79747E),
            OutlineVariant      = C(0xFFCAC4D0),
            InverseSurface      = C(0xFF313033),
            InverseOnSurface    = C(0xFFF4EFF4),
            InversePrimary      = C(0xFFFFB4AB),
        };

        private static readonly MusicefyColorScheme DefaultDark = new()
        {
            IsDark = true,
            Primary             = C(0xFFFFB4AB),
            OnPrimary           = C(0xFF680003),
            PrimaryContainer    = C(0xFF930006),
            OnPrimaryContainer  = C(0xFFFFDAD4),
            Secondary           = C(0xFFE7BDB9),
            OnSecondary         = C(0xFF442927),
            SecondaryContainer  = C(0xFF5D3F3C),
            OnSecondaryContainer= C(0xFFFFDAD4),
            Tertiary            = C(0xFFDBC36E),
            OnTertiary          = C(0xFF3C2E00),
            TertiaryContainer   = C(0xFF564400),
            OnTertiaryContainer = C(0xFFFCDFA6),
            Error               = C(0xFFF2B8B5),
            OnError             = C(0xFF601410),
            ErrorContainer      = C(0xFF8C1D18),
            OnErrorContainer    = C(0xFFF9DEDC),
            Surface             = C(0xFF141218),
            OnSurface           = C(0xFFE6E0E9),
            SurfaceVariant      = C(0xFF49454F),
            OnSurfaceVariant    = C(0xFFCAC4D0),
            SurfaceContainerLowest  = C(0xFF0F0D13),
            SurfaceContainerLow     = C(0xFF1D1B20),
            SurfaceContainer        = C(0xFF211F26),
            SurfaceContainerHigh    = C(0xFF2B2930),
            SurfaceContainerHighest = C(0xFF36343B),
            Outline             = C(0xFF938F99),
            OutlineVariant      = C(0xFF49454F),
            InverseSurface      = C(0xFFE6E0E9),
            InverseOnSurface    = C(0xFF313033),
            InversePrimary      = C(0xFFB5261E),
        };

        // ── Green Apple ──────────────────────────────────────────────────────

        private static readonly MusicefyColorScheme GreenAppleLight = new()
        {
            IsDark = false,
            Primary             = C(0xFF386A20),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFB7F397),
            OnPrimaryContainer  = C(0xFF042100),
            Secondary           = C(0xFF54624D),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFD7E8CD),
            OnSecondaryContainer= C(0xFF131F0E),
            Tertiary            = C(0xFF386667),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFBBEBED),
            OnTertiaryContainer = C(0xFF002022),
            Error               = C(0xFFBA1A1A),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFFFDAD6),
            OnErrorContainer    = C(0xFF410002),
            Surface             = C(0xFFF8FBF2),
            OnSurface           = C(0xFF1A1C18),
            SurfaceVariant      = C(0xFFDFE4D8),
            OnSurfaceVariant    = C(0xFF43483E),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFF2F5EC),
            SurfaceContainer        = C(0xFFECEFE6),
            SurfaceContainerHigh    = C(0xFFE6EAE1),
            SurfaceContainerHighest = C(0xFFE1E4DB),
            Outline             = C(0xFF73786E),
            OutlineVariant      = C(0xFFC3C8BC),
            InverseSurface      = C(0xFF2F312D),
            InverseOnSurface    = C(0xFFF1F1EC),
            InversePrimary      = C(0xFF9CD67D),
        };

        private static readonly MusicefyColorScheme GreenAppleDark = new()
        {
            IsDark = true,
            Primary             = C(0xFF9CD67D),
            OnPrimary           = C(0xFF0E3900),
            PrimaryContainer    = C(0xFF1F5200),
            OnPrimaryContainer  = C(0xFFB7F397),
            Secondary           = C(0xFFBBCBB1),
            OnSecondary         = C(0xFF263421),
            SecondaryContainer  = C(0xFF3D4B37),
            OnSecondaryContainer= C(0xFFD7E8CD),
            Tertiary            = C(0xFFA0CFD0),
            OnTertiary          = C(0xFF003738),
            TertiaryContainer   = C(0xFF1D4E50),
            OnTertiaryContainer = C(0xFFBBEBED),
            Error               = C(0xFFFFB4AB),
            OnError             = C(0xFF690005),
            ErrorContainer      = C(0xFF93000A),
            OnErrorContainer    = C(0xFFFFDAD6),
            Surface             = C(0xFF121410),
            OnSurface           = C(0xFFE2E3DC),
            SurfaceVariant      = C(0xFF43483E),
            OnSurfaceVariant    = C(0xFFC3C8BC),
            SurfaceContainerLowest  = C(0xFF0D0F0B),
            SurfaceContainerLow     = C(0xFF1A1C18),
            SurfaceContainer        = C(0xFF1E211C),
            SurfaceContainerHigh    = C(0xFF292B26),
            SurfaceContainerHighest = C(0xFF333631),
            Outline             = C(0xFF8D9289),
            OutlineVariant      = C(0xFF43483E),
            InverseSurface      = C(0xFFE2E3DC),
            InverseOnSurface    = C(0xFF2F312D),
            InversePrimary      = C(0xFF386A20),
        };

        // ── Lavender ─────────────────────────────────────────────────────────

        private static readonly MusicefyColorScheme LavenderLight = new()
        {
            IsDark = false,
            Primary             = C(0xFF6750A4),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFEADDFF),
            OnPrimaryContainer  = C(0xFF21005D),
            Secondary           = C(0xFF625B71),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFE8DEF8),
            OnSecondaryContainer= C(0xFF1D192B),
            Tertiary            = C(0xFF7D5260),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFFFD8E4),
            OnTertiaryContainer = C(0xFF31111D),
            Error               = C(0xFFB3261E),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFF9DEDC),
            OnErrorContainer    = C(0xFF410E0B),
            Surface             = C(0xFFFFFBFE),
            OnSurface           = C(0xFF1C1B1F),
            SurfaceVariant      = C(0xFFE7E0EC),
            OnSurfaceVariant    = C(0xFF49454F),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFF7F2FA),
            SurfaceContainer        = C(0xFFF3EDF7),
            SurfaceContainerHigh    = C(0xFFECE6F0),
            SurfaceContainerHighest = C(0xFFE6E0E9),
            Outline             = C(0xFF79747E),
            OutlineVariant      = C(0xFFCAC4D0),
            InverseSurface      = C(0xFF313033),
            InverseOnSurface    = C(0xFFF4EFF4),
            InversePrimary      = C(0xFFD0BCFF),
        };

        private static readonly MusicefyColorScheme LavenderDark = new()
        {
            IsDark = true,
            Primary             = C(0xFFD0BCFF),
            OnPrimary           = C(0xFF381E72),
            PrimaryContainer    = C(0xFF4F378B),
            OnPrimaryContainer  = C(0xFFEADDFF),
            Secondary           = C(0xFFCCC2DC),
            OnSecondary         = C(0xFF332D41),
            SecondaryContainer  = C(0xFF4A4458),
            OnSecondaryContainer= C(0xFFE8DEF8),
            Tertiary            = C(0xFFEFB8C8),
            OnTertiary          = C(0xFF492532),
            TertiaryContainer   = C(0xFF633B48),
            OnTertiaryContainer = C(0xFFFFD8E4),
            Error               = C(0xFFF2B8B5),
            OnError             = C(0xFF601410),
            ErrorContainer      = C(0xFF8C1D18),
            OnErrorContainer    = C(0xFFF9DEDC),
            Surface             = C(0xFF141218),
            OnSurface           = C(0xFFE6E0E9),
            SurfaceVariant      = C(0xFF49454F),
            OnSurfaceVariant    = C(0xFFCAC4D0),
            SurfaceContainerLowest  = C(0xFF0F0D13),
            SurfaceContainerLow     = C(0xFF1D1B20),
            SurfaceContainer        = C(0xFF211F26),
            SurfaceContainerHigh    = C(0xFF2B2930),
            SurfaceContainerHighest = C(0xFF36343B),
            Outline             = C(0xFF938F99),
            OutlineVariant      = C(0xFF49454F),
            InverseSurface      = C(0xFFE6E0E9),
            InverseOnSurface    = C(0xFF313033),
            InversePrimary      = C(0xFF6750A4),
        };

        // ── Strawberry Daiquiri ──────────────────────────────────────────────

        private static readonly MusicefyColorScheme StrawberryDaiquiriLight = new()
        {
            IsDark = false,
            Primary             = C(0xFFB5166B),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFFFD9E3),
            OnPrimaryContainer  = C(0xFF3E001E),
            Secondary           = C(0xFF74565F),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFFFD9E3),
            OnSecondaryContainer= C(0xFF2B151C),
            Tertiary            = C(0xFF7C5635),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFFFDCC4),
            OnTertiaryContainer = C(0xFF2E1500),
            Error               = C(0xFFBA1A1A),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFFFDAD6),
            OnErrorContainer    = C(0xFF410002),
            Surface             = C(0xFFFFFBFF),
            OnSurface           = C(0xFF201A1C),
            SurfaceVariant      = C(0xFFF2DDE2),
            OnSurfaceVariant    = C(0xFF514347),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFFBF0F2),
            SurfaceContainer        = C(0xFFF5EAEC),
            SurfaceContainerHigh    = C(0xFFEFE4E6),
            SurfaceContainerHighest = C(0xFFE9DEE0),
            Outline             = C(0xFF837376),
            OutlineVariant      = C(0xFFD5C2C6),
            InverseSurface      = C(0xFF362F30),
            InverseOnSurface    = C(0xFFFBECEF),
            InversePrimary      = C(0xFFFFB1C7),
        };

        private static readonly MusicefyColorScheme StrawberryDaiquiriDark = new()
        {
            IsDark = true,
            Primary             = C(0xFFFFB1C7),
            OnPrimary           = C(0xFF650034),
            PrimaryContainer    = C(0xFF8E1050),
            OnPrimaryContainer  = C(0xFFFFD9E3),
            Secondary           = C(0xFFE3BDC6),
            OnSecondary         = C(0xFF422931),
            SecondaryContainer  = C(0xFF5A3F47),
            OnSecondaryContainer= C(0xFFFFD9E3),
            Tertiary            = C(0xFFEFBD94),
            OnTertiary          = C(0xFF48290D),
            TertiaryContainer   = C(0xFF613F22),
            OnTertiaryContainer = C(0xFFFFDCC4),
            Error               = C(0xFFFFB4AB),
            OnError             = C(0xFF690005),
            ErrorContainer      = C(0xFF93000A),
            OnErrorContainer    = C(0xFFFFDAD6),
            Surface             = C(0xFF181113),
            OnSurface           = C(0xFFE9DEE0),
            SurfaceVariant      = C(0xFF514347),
            OnSurfaceVariant    = C(0xFFD5C2C6),
            SurfaceContainerLowest  = C(0xFF130C0E),
            SurfaceContainerLow     = C(0xFF201A1C),
            SurfaceContainer        = C(0xFF241E20),
            SurfaceContainerHigh    = C(0xFF2F282A),
            SurfaceContainerHighest = C(0xFF3A3334),
            Outline             = C(0xFF9E8E91),
            OutlineVariant      = C(0xFF514347),
            InverseSurface      = C(0xFFE9DEE0),
            InverseOnSurface    = C(0xFF362F30),
            InversePrimary      = C(0xFFB5166B),
        };

        // ── Midnight Dusk ────────────────────────────────────────────────────

        private static readonly MusicefyColorScheme MidnightDuskLight = new()
        {
            IsDark = false,
            Primary             = C(0xFF4355B9),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFDCE1FF),
            OnPrimaryContainer  = C(0xFF00105C),
            Secondary           = C(0xFF5A5D72),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFDFE1F9),
            OnSecondaryContainer= C(0xFF171A2C),
            Tertiary            = C(0xFF76546E),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFFFD7F3),
            OnTertiaryContainer = C(0xFF2D1228),
            Error               = C(0xFFBA1A1A),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFFFDAD6),
            OnErrorContainer    = C(0xFF410002),
            Surface             = C(0xFFFFFBFF),
            OnSurface           = C(0xFF1B1B21),
            SurfaceVariant      = C(0xFFE2E1EC),
            OnSurfaceVariant    = C(0xFF45464F),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFF4F4FC),
            SurfaceContainer        = C(0xFFEEEEF6),
            SurfaceContainerHigh    = C(0xFFE8E8F0),
            SurfaceContainerHighest = C(0xFFE3E2EB),
            Outline             = C(0xFF767680),
            OutlineVariant      = C(0xFFC6C5D0),
            InverseSurface      = C(0xFF303036),
            InverseOnSurface    = C(0xFFF2F0FA),
            InversePrimary      = C(0xFFB5C4FF),
        };

        private static readonly MusicefyColorScheme MidnightDuskDark = new()
        {
            IsDark = true,
            Primary             = C(0xFFB5C4FF),
            OnPrimary           = C(0xFF0C1A60),
            PrimaryContainer    = C(0xFF2A3C8E),
            OnPrimaryContainer  = C(0xFFDCE1FF),
            Secondary           = C(0xFFC3C5DD),
            OnSecondary         = C(0xFF2C2F42),
            SecondaryContainer  = C(0xFF434659),
            OnSecondaryContainer= C(0xFFDFE1F9),
            Tertiary            = C(0xFFE5BAD8),
            OnTertiary          = C(0xFF44273E),
            TertiaryContainer   = C(0xFF5C3D55),
            OnTertiaryContainer = C(0xFFFFD7F3),
            Error               = C(0xFFFFB4AB),
            OnError             = C(0xFF690005),
            ErrorContainer      = C(0xFF93000A),
            OnErrorContainer    = C(0xFFFFDAD6),
            Surface             = C(0xFF121318),
            OnSurface           = C(0xFFE3E1EC),
            SurfaceVariant      = C(0xFF45464F),
            OnSurfaceVariant    = C(0xFFC6C5D0),
            SurfaceContainerLowest  = C(0xFF0D0E13),
            SurfaceContainerLow     = C(0xFF1B1B21),
            SurfaceContainer        = C(0xFF1F1F25),
            SurfaceContainerHigh    = C(0xFF292A30),
            SurfaceContainerHighest = C(0xFF34343B),
            Outline             = C(0xFF90909A),
            OutlineVariant      = C(0xFF45464F),
            InverseSurface      = C(0xFFE3E1EC),
            InverseOnSurface    = C(0xFF303036),
            InversePrimary      = C(0xFF4355B9),
        };

        // ── Tako ─────────────────────────────────────────────────────────────

        private static readonly MusicefyColorScheme TakoLight = new()
        {
            IsDark = false,
            Primary             = C(0xFF6B5E10),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFF9E287),
            OnPrimaryContainer  = C(0xFF201C00),
            Secondary           = C(0xFF665E41),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFEEE3BC),
            OnSecondaryContainer= C(0xFF211C04),
            Tertiary            = C(0xFF436651),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFC6ECD1),
            OnTertiaryContainer = C(0xFF002112),
            Error               = C(0xFFBA1A1A),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFFFDAD6),
            OnErrorContainer    = C(0xFF410002),
            Surface             = C(0xFFFFF9EF),
            OnSurface           = C(0xFF1D1B13),
            SurfaceVariant      = C(0xFFEAE2CF),
            OnSurfaceVariant    = C(0xFF4B4635),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFF8F2E6),
            SurfaceContainer        = C(0xFFF2ECE0),
            SurfaceContainerHigh    = C(0xFFECE7DA),
            SurfaceContainerHighest = C(0xFFE6E1D4),
            Outline             = C(0xFF7D7764),
            OutlineVariant      = C(0xFFCEC6B3),
            InverseSurface      = C(0xFF333027),
            InverseOnSurface    = C(0xFFF5F0E3),
            InversePrimary      = C(0xFFDCC64E),
        };

        private static readonly MusicefyColorScheme TakoDark = new()
        {
            IsDark = true,
            Primary             = C(0xFFDCC64E),
            OnPrimary           = C(0xFF383100),
            PrimaryContainer    = C(0xFF514700),
            OnPrimaryContainer  = C(0xFFF9E287),
            Secondary           = C(0xFFD1C7A2),
            OnSecondary         = C(0xFF373116),
            SecondaryContainer  = C(0xFF4E472B),
            OnSecondaryContainer= C(0xFFEEE3BC),
            Tertiary            = C(0xFFAAD0B6),
            OnTertiary          = C(0xFF153726),
            TertiaryContainer   = C(0xFF2D4E3C),
            OnTertiaryContainer = C(0xFFC6ECD1),
            Error               = C(0xFFFFB4AB),
            OnError             = C(0xFF690005),
            ErrorContainer      = C(0xFF93000A),
            OnErrorContainer    = C(0xFFFFDAD6),
            Surface             = C(0xFF15130B),
            OnSurface           = C(0xFFE6E1D4),
            SurfaceVariant      = C(0xFF4B4635),
            OnSurfaceVariant    = C(0xFFCEC6B3),
            SurfaceContainerLowest  = C(0xFF100E07),
            SurfaceContainerLow     = C(0xFF1D1B13),
            SurfaceContainer        = C(0xFF211F17),
            SurfaceContainerHigh    = C(0xFF2C2A21),
            SurfaceContainerHighest = C(0xFF36342B),
            Outline             = C(0xFF979180),
            OutlineVariant      = C(0xFF4B4635),
            InverseSurface      = C(0xFFE6E1D4),
            InverseOnSurface    = C(0xFF333027),
            InversePrimary      = C(0xFF6B5E10),
        };

        // ── Teal Turquoise ───────────────────────────────────────────────────

        private static readonly MusicefyColorScheme TealTurquoiseLight = new()
        {
            IsDark = false,
            Primary             = C(0xFF006A60),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFF9CF2E2),
            OnPrimaryContainer  = C(0xFF00201C),
            Secondary           = C(0xFF4A635D),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFCCE8DF),
            OnSecondaryContainer= C(0xFF06201A),
            Tertiary            = C(0xFF446279),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFCBE7FF),
            OnTertiaryContainer = C(0xFF001E30),
            Error               = C(0xFFBA1A1A),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFFFDAD6),
            OnErrorContainer    = C(0xFF410002),
            Surface             = C(0xFFF5FBF8),
            OnSurface           = C(0xFF171D1B),
            SurfaceVariant      = C(0xFFDAE5E0),
            OnSurfaceVariant    = C(0xFF3F4945),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFEFF5F2),
            SurfaceContainer        = C(0xFFE9EFEC),
            SurfaceContainerHigh    = C(0xFFE3EAE6),
            SurfaceContainerHighest = C(0xFFDEE4E1),
            Outline             = C(0xFF6F7975),
            OutlineVariant      = C(0xFFBEC9C4),
            InverseSurface      = C(0xFF2B3230),
            InverseOnSurface    = C(0xFFECF2EE),
            InversePrimary      = C(0xFF80D5C6),
        };

        private static readonly MusicefyColorScheme TealTurquoiseDark = new()
        {
            IsDark = true,
            Primary             = C(0xFF80D5C6),
            OnPrimary           = C(0xFF003731),
            PrimaryContainer    = C(0xFF005049),
            OnPrimaryContainer  = C(0xFF9CF2E2),
            Secondary           = C(0xFFB1CCC3),
            OnSecondary         = C(0xFF1C352F),
            SecondaryContainer  = C(0xFF334B45),
            OnSecondaryContainer= C(0xFFCCE8DF),
            Tertiary            = C(0xFFADCAE5),
            OnTertiary          = C(0xFF133348),
            TertiaryContainer   = C(0xFF2C4A60),
            OnTertiaryContainer = C(0xFFCBE7FF),
            Error               = C(0xFFFFB4AB),
            OnError             = C(0xFF690005),
            ErrorContainer      = C(0xFF93000A),
            OnErrorContainer    = C(0xFFFFDAD6),
            Surface             = C(0xFF0E1513),
            OnSurface           = C(0xFFDEE4E1),
            SurfaceVariant      = C(0xFF3F4945),
            OnSurfaceVariant    = C(0xFFBEC9C4),
            SurfaceContainerLowest  = C(0xFF090F0E),
            SurfaceContainerLow     = C(0xFF171D1B),
            SurfaceContainer        = C(0xFF1B2120),
            SurfaceContainerHigh    = C(0xFF262C2A),
            SurfaceContainerHighest = C(0xFF313735),
            Outline             = C(0xFF899390),
            OutlineVariant      = C(0xFF3F4945),
            InverseSurface      = C(0xFFDEE4E1),
            InverseOnSurface    = C(0xFF2B3230),
            InversePrimary      = C(0xFF006A60),
        };

        // ── Tidal Wave ───────────────────────────────────────────────────────

        private static readonly MusicefyColorScheme TidalWaveLight = new()
        {
            IsDark = false,
            Primary             = C(0xFF00658C),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFC6E7FF),
            OnPrimaryContainer  = C(0xFF001E30),
            Secondary           = C(0xFF4F616E),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFD2E5F5),
            OnSecondaryContainer= C(0xFF0B1D28),
            Tertiary            = C(0xFF63597C),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFE9DDFF),
            OnTertiaryContainer = C(0xFF1F1635),
            Error               = C(0xFFBA1A1A),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFFFDAD6),
            OnErrorContainer    = C(0xFF410002),
            Surface             = C(0xFFF6FAFE),
            OnSurface           = C(0xFF171C1F),
            SurfaceVariant      = C(0xFFDDE3EA),
            OnSurfaceVariant    = C(0xFF41484D),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFF0F4F8),
            SurfaceContainer        = C(0xFFEBEEF2),
            SurfaceContainerHigh    = C(0xFFE5E8ED),
            SurfaceContainerHighest = C(0xFFDFE3E7),
            Outline             = C(0xFF71787E),
            OutlineVariant      = C(0xFFC1C7CE),
            InverseSurface      = C(0xFF2C3134),
            InverseOnSurface    = C(0xFFECF1F5),
            InversePrimary      = C(0xFF7ED0FF),
        };

        private static readonly MusicefyColorScheme TidalWaveDark = new()
        {
            IsDark = true,
            Primary             = C(0xFF7ED0FF),
            OnPrimary           = C(0xFF00344D),
            PrimaryContainer    = C(0xFF004C6D),
            OnPrimaryContainer  = C(0xFFC6E7FF),
            Secondary           = C(0xFFB6C9D8),
            OnSecondary         = C(0xFF21323E),
            SecondaryContainer  = C(0xFF384956),
            OnSecondaryContainer= C(0xFFD2E5F5),
            Tertiary            = C(0xFFCFC0E8),
            OnTertiary          = C(0xFF352B4B),
            TertiaryContainer   = C(0xFF4C4163),
            OnTertiaryContainer = C(0xFFE9DDFF),
            Error               = C(0xFFFFB4AB),
            OnError             = C(0xFF690005),
            ErrorContainer      = C(0xFF93000A),
            OnErrorContainer    = C(0xFFFFDAD6),
            Surface             = C(0xFF0F1417),
            OnSurface           = C(0xFFDFE3E7),
            SurfaceVariant      = C(0xFF41484D),
            OnSurfaceVariant    = C(0xFFC1C7CE),
            SurfaceContainerLowest  = C(0xFF0A0F11),
            SurfaceContainerLow     = C(0xFF171C1F),
            SurfaceContainer        = C(0xFF1B2023),
            SurfaceContainerHigh    = C(0xFF262B2E),
            SurfaceContainerHighest = C(0xFF313639),
            Outline             = C(0xFF8B9298),
            OutlineVariant      = C(0xFF41484D),
            InverseSurface      = C(0xFFDFE3E7),
            InverseOnSurface    = C(0xFF2C3134),
            InversePrimary      = C(0xFF00658C),
        };

        // ── Cotton Candy ─────────────────────────────────────────────────────

        private static readonly MusicefyColorScheme CottonCandyLight = new()
        {
            IsDark = false,
            Primary             = C(0xFF9C4040),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFFFDAD6),
            OnPrimaryContainer  = C(0xFF3B0909),
            Secondary           = C(0xFF775652),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFFFDAD6),
            OnSecondaryContainer= C(0xFF2C1512),
            Tertiary            = C(0xFF705C2E),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFFBDFA6),
            OnTertiaryContainer = C(0xFF261A00),
            Error               = C(0xFFBA1A1A),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFFFDAD6),
            OnErrorContainer    = C(0xFF410002),
            Surface             = C(0xFFFFFBFF),
            OnSurface           = C(0xFF201A19),
            SurfaceVariant      = C(0xFFF5DDDA),
            OnSurfaceVariant    = C(0xFF534341),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFFEF0EE),
            SurfaceContainer        = C(0xFFF9EAE7),
            SurfaceContainerHigh    = C(0xFFF3E4E1),
            SurfaceContainerHighest = C(0xFFEDDEDB),
            Outline             = C(0xFF857370),
            OutlineVariant      = C(0xFFD8C2BE),
            InverseSurface      = C(0xFF362F2E),
            InverseOnSurface    = C(0xFFFBEDEB),
            InversePrimary      = C(0xFFFFB4AB),
        };

        private static readonly MusicefyColorScheme CottonCandyDark = new()
        {
            IsDark = true,
            Primary             = C(0xFFFFB4AB),
            OnPrimary           = C(0xFF5F1313),
            PrimaryContainer    = C(0xFF7D2A2A),
            OnPrimaryContainer  = C(0xFFFFDAD6),
            Secondary           = C(0xFFE7BDB9),
            OnSecondary         = C(0xFF442927),
            SecondaryContainer  = C(0xFF5D3F3C),
            OnSecondaryContainer= C(0xFFFFDAD6),
            Tertiary            = C(0xFFDEC36E),
            OnTertiary          = C(0xFF3C2E00),
            TertiaryContainer   = C(0xFF564400),
            OnTertiaryContainer = C(0xFFFBDFA6),
            Error               = C(0xFFFFB4AB),
            OnError             = C(0xFF690005),
            ErrorContainer      = C(0xFF93000A),
            OnErrorContainer    = C(0xFFFFDAD6),
            Surface             = C(0xFF181212),
            OnSurface           = C(0xFFEDDEDB),
            SurfaceVariant      = C(0xFF534341),
            OnSurfaceVariant    = C(0xFFD8C2BE),
            SurfaceContainerLowest  = C(0xFF130C0C),
            SurfaceContainerLow     = C(0xFF201A19),
            SurfaceContainer        = C(0xFF241E1D),
            SurfaceContainerHigh    = C(0xFF2F2827),
            SurfaceContainerHighest = C(0xFF3A3331),
            Outline             = C(0xFFA08C89),
            OutlineVariant      = C(0xFF534341),
            InverseSurface      = C(0xFFEDDEDB),
            InverseOnSurface    = C(0xFF362F2E),
            InversePrimary      = C(0xFF9C4040),
        };

        // ── Cloudflare ───────────────────────────────────────────────────────

        private static readonly MusicefyColorScheme CloudflareLight = new()
        {
            IsDark = false,
            Primary             = C(0xFFF06000),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFFFDCC8),
            OnPrimaryContainer  = C(0xFF331400),
            Secondary           = C(0xFF725C50),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFFFDCC8),
            OnSecondaryContainer= C(0xFF2A1700),
            Tertiary            = C(0xFF59633A),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFDDE8B4),
            OnTertiaryContainer = C(0xFF171E00),
            Error               = C(0xFFBA1A1A),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFFFDAD6),
            OnErrorContainer    = C(0xFF410002),
            Surface             = C(0xFFFFFBFF),
            OnSurface           = C(0xFF201A17),
            SurfaceVariant      = C(0xFFF3DFD2),
            OnSurfaceVariant    = C(0xFF51443A),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFFBF0E8),
            SurfaceContainer        = C(0xFFF5EAE2),
            SurfaceContainerHigh    = C(0xFFEFE4DC),
            SurfaceContainerHighest = C(0xFFE9DED6),
            Outline             = C(0xFF837468),
            OutlineVariant      = C(0xFFD6C3B6),
            InverseSurface      = C(0xFF362F2B),
            InverseOnSurface    = C(0xFFF9EFE7),
            InversePrimary      = C(0xFFFFB786),
        };

        private static readonly MusicefyColorScheme CloudflareDark = new()
        {
            IsDark = true,
            Primary             = C(0xFFFFB786),
            OnPrimary           = C(0xFF532200),
            PrimaryContainer    = C(0xFFB74600),
            OnPrimaryContainer  = C(0xFFFFDCC8),
            Secondary           = C(0xFFE0C1AD),
            OnSecondary         = C(0xFF402D20),
            SecondaryContainer  = C(0xFF594335),
            OnSecondaryContainer= C(0xFFFFDCC8),
            Tertiary            = C(0xFFC1CC9A),
            OnTertiary          = C(0xFF2C360F),
            TertiaryContainer   = C(0xFF434D24),
            OnTertiaryContainer = C(0xFFDDE8B4),
            Error               = C(0xFFFFB4AB),
            OnError             = C(0xFF690005),
            ErrorContainer      = C(0xFF93000A),
            OnErrorContainer    = C(0xFFFFDAD6),
            Surface             = C(0xFF181210),
            OnSurface           = C(0xFFE9DED6),
            SurfaceVariant      = C(0xFF51443A),
            OnSurfaceVariant    = C(0xFFD6C3B6),
            SurfaceContainerLowest  = C(0xFF120C0A),
            SurfaceContainerLow     = C(0xFF201A17),
            SurfaceContainer        = C(0xFF241E1B),
            SurfaceContainerHigh    = C(0xFF2F2825),
            SurfaceContainerHighest = C(0xFF3A3330),
            Outline             = C(0xFF9E8E82),
            OutlineVariant      = C(0xFF51443A),
            InverseSurface      = C(0xFFE9DED6),
            InverseOnSurface    = C(0xFF362F2B),
            InversePrimary      = C(0xFFF06000),
        };

        // ── Doom ─────────────────────────────────────────────────────────────

        private static readonly MusicefyColorScheme DoomLight = new()
        {
            IsDark = false,
            Primary             = C(0xFFB5241E),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFFFDAD5),
            OnPrimaryContainer  = C(0xFF410001),
            Secondary           = C(0xFF775652),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFFFDAD5),
            OnSecondaryContainer= C(0xFF2C1512),
            Tertiary            = C(0xFF6F5D2E),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFF9E1A6),
            OnTertiaryContainer = C(0xFF251A00),
            Error               = C(0xFFBA1A1A),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFFFDAD6),
            OnErrorContainer    = C(0xFF410002),
            Surface             = C(0xFFFFFBFF),
            OnSurface           = C(0xFF201A19),
            SurfaceVariant      = C(0xFFF5DDDA),
            OnSurfaceVariant    = C(0xFF534341),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFFEF0EE),
            SurfaceContainer        = C(0xFFF9EAE8),
            SurfaceContainerHigh    = C(0xFFF3E4E2),
            SurfaceContainerHighest = C(0xFFEDDEDC),
            Outline             = C(0xFF857370),
            OutlineVariant      = C(0xFFD8C2BE),
            InverseSurface      = C(0xFF362F2E),
            InverseOnSurface    = C(0xFFFBEDEB),
            InversePrimary      = C(0xFFFFB4A9),
        };

        private static readonly MusicefyColorScheme DoomDark = new()
        {
            IsDark = true,
            Primary             = C(0xFFFFB4A9),
            OnPrimary           = C(0xFF690002),
            PrimaryContainer    = C(0xFF8E0D07),
            OnPrimaryContainer  = C(0xFFFFDAD5),
            Secondary           = C(0xFFE7BDB8),
            OnSecondary         = C(0xFF442926),
            SecondaryContainer  = C(0xFF5D3F3B),
            OnSecondaryContainer= C(0xFFFFDAD5),
            Tertiary            = C(0xFFDCC58D),
            OnTertiary          = C(0xFF3D2F04),
            TertiaryContainer   = C(0xFF554619),
            OnTertiaryContainer = C(0xFFF9E1A6),
            Error               = C(0xFFFFB4AB),
            OnError             = C(0xFF690005),
            ErrorContainer      = C(0xFF93000A),
            OnErrorContainer    = C(0xFFFFDAD6),
            Surface             = C(0xFF181211),
            OnSurface           = C(0xFFEDDEDC),
            SurfaceVariant      = C(0xFF534341),
            OnSurfaceVariant    = C(0xFFD8C2BE),
            SurfaceContainerLowest  = C(0xFF130C0C),
            SurfaceContainerLow     = C(0xFF201A19),
            SurfaceContainer        = C(0xFF241E1D),
            SurfaceContainerHigh    = C(0xFF2F2827),
            SurfaceContainerHighest = C(0xFF3A3332),
            Outline             = C(0xFFA08C89),
            OutlineVariant      = C(0xFF534341),
            InverseSurface      = C(0xFFEDDEDC),
            InverseOnSurface    = C(0xFF362F2E),
            InversePrimary      = C(0xFFB5241E),
        };

        // ── Mocha ────────────────────────────────────────────────────────────

        private static readonly MusicefyColorScheme MochaLight = new()
        {
            IsDark = false,
            Primary             = C(0xFF7B5800),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFFFDEA6),
            OnPrimaryContainer  = C(0xFF261900),
            Secondary           = C(0xFF6B5D3F),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFF4E1BB),
            OnSecondaryContainer= C(0xFF241A04),
            Tertiary            = C(0xFF4E6544),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFD1EBCC),
            OnTertiaryContainer = C(0xFF0C2008),
            Error               = C(0xFFBA1A1A),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFFFDAD6),
            OnErrorContainer    = C(0xFF410002),
            Surface             = C(0xFFFFF8F0),
            OnSurface           = C(0xFF1E1B16),
            SurfaceVariant      = C(0xFFECE1CF),
            OnSurfaceVariant    = C(0xFF4D4639),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFF8F2E8),
            SurfaceContainer        = C(0xFFF2ECE2),
            SurfaceContainerHigh    = C(0xFFEDE6DC),
            SurfaceContainerHighest = C(0xFFE7E1D7),
            Outline             = C(0xFF7F7667),
            OutlineVariant      = C(0xFFD0C5B4),
            InverseSurface      = C(0xFF34302A),
            InverseOnSurface    = C(0xFFF6F0E5),
            InversePrimary      = C(0xFFF5BD48),
        };

        private static readonly MusicefyColorScheme MochaDark = new()
        {
            IsDark = true,
            Primary             = C(0xFFF5BD48),
            OnPrimary           = C(0xFF402D00),
            PrimaryContainer    = C(0xFF5C4200),
            OnPrimaryContainer  = C(0xFFFFDEA6),
            Secondary           = C(0xFFD7C5A1),
            OnSecondary         = C(0xFF3A2F15),
            SecondaryContainer  = C(0xFF52452A),
            OnSecondaryContainer= C(0xFFF4E1BB),
            Tertiary            = C(0xFFB5CFB2),
            OnTertiary          = C(0xFF223721),
            TertiaryContainer   = C(0xFF384E36),
            OnTertiaryContainer = C(0xFFD1EBCC),
            Error               = C(0xFFFFB4AB),
            OnError             = C(0xFF690005),
            ErrorContainer      = C(0xFF93000A),
            OnErrorContainer    = C(0xFFFFDAD6),
            Surface             = C(0xFF16130E),
            OnSurface           = C(0xFFE7E1D7),
            SurfaceVariant      = C(0xFF4D4639),
            OnSurfaceVariant    = C(0xFFD0C5B4),
            SurfaceContainerLowest  = C(0xFF100D09),
            SurfaceContainerLow     = C(0xFF1E1B16),
            SurfaceContainer        = C(0xFF221F1A),
            SurfaceContainerHigh    = C(0xFF2D2A24),
            SurfaceContainerHighest = C(0xFF38342F),
            Outline             = C(0xFF99907F),
            OutlineVariant      = C(0xFF4D4639),
            InverseSurface      = C(0xFFE7E1D7),
            InverseOnSurface    = C(0xFF34302A),
            InversePrimary      = C(0xFF7B5800),
        };

        // ── Sapphire ─────────────────────────────────────────────────────────

        private static readonly MusicefyColorScheme SapphireLight = new()
        {
            IsDark = false,
            Primary             = C(0xFF3E5BA9),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFDCE1FF),
            OnPrimaryContainer  = C(0xFF00164F),
            Secondary           = C(0xFF585E71),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFDCE2F9),
            OnSecondaryContainer= C(0xFF151B2C),
            Tertiary            = C(0xFF745574),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFFFD6F8),
            OnTertiaryContainer = C(0xFF2B132C),
            Error               = C(0xFFBA1A1A),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFFFDAD6),
            OnErrorContainer    = C(0xFF410002),
            Surface             = C(0xFFFAF8FF),
            OnSurface           = C(0xFF1A1B21),
            SurfaceVariant      = C(0xFFE1E2EC),
            OnSurfaceVariant    = C(0xFF44464F),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFF4F3FC),
            SurfaceContainer        = C(0xFFEEEDF6),
            SurfaceContainerHigh    = C(0xFFE8E7F1),
            SurfaceContainerHighest = C(0xFFE3E2EB),
            Outline             = C(0xFF757680),
            OutlineVariant      = C(0xFFC5C6D0),
            InverseSurface      = C(0xFF2F3036),
            InverseOnSurface    = C(0xFFF1F0FA),
            InversePrimary      = C(0xFFB5C4FF),
        };

        private static readonly MusicefyColorScheme SapphireDark = new()
        {
            IsDark = true,
            Primary             = C(0xFFB5C4FF),
            OnPrimary           = C(0xFF08218A),
            PrimaryContainer    = C(0xFF253E8F),
            OnPrimaryContainer  = C(0xFFDCE1FF),
            Secondary           = C(0xFFC0C6DD),
            OnSecondary         = C(0xFF2A3041),
            SecondaryContainer  = C(0xFF404659),
            OnSecondaryContainer= C(0xFFDCE2F9),
            Tertiary            = C(0xFFE2BBE3),
            OnTertiary          = C(0xFF422743),
            TertiaryContainer   = C(0xFF5A3D5B),
            OnTertiaryContainer = C(0xFFFFD6F8),
            Error               = C(0xFFFFB4AB),
            OnError             = C(0xFF690005),
            ErrorContainer      = C(0xFF93000A),
            OnErrorContainer    = C(0xFFFFDAD6),
            Surface             = C(0xFF121318),
            OnSurface           = C(0xFFE3E2EB),
            SurfaceVariant      = C(0xFF44464F),
            OnSurfaceVariant    = C(0xFFC5C6D0),
            SurfaceContainerLowest  = C(0xFF0D0E13),
            SurfaceContainerLow     = C(0xFF1A1B21),
            SurfaceContainer        = C(0xFF1E1F25),
            SurfaceContainerHigh    = C(0xFF292A30),
            SurfaceContainerHighest = C(0xFF33343B),
            Outline             = C(0xFF8E9099),
            OutlineVariant      = C(0xFF44464F),
            InverseSurface      = C(0xFFE3E2EB),
            InverseOnSurface    = C(0xFF2F3036),
            InversePrimary      = C(0xFF3E5BA9),
        };

        // ── Nord ─────────────────────────────────────────────────────────────

        private static readonly MusicefyColorScheme NordLight = new()
        {
            IsDark = false,
            Primary             = C(0xFF4A607B),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFD1E4FF),
            OnPrimaryContainer  = C(0xFF021D36),
            Secondary           = C(0xFF535F70),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFD6E4F7),
            OnSecondaryContainer= C(0xFF101C2B),
            Tertiary            = C(0xFF6B5677),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFF2DAFF),
            OnTertiaryContainer = C(0xFF251431),
            Error               = C(0xFFBA1A1A),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFFFDAD6),
            OnErrorContainer    = C(0xFF410002),
            Surface             = C(0xFFF7F9FF),
            OnSurface           = C(0xFF181C20),
            SurfaceVariant      = C(0xFFDFE2EB),
            OnSurfaceVariant    = C(0xFF434750),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFF1F3FA),
            SurfaceContainer        = C(0xFFEBEEF5),
            SurfaceContainerHigh    = C(0xFFE5E8EF),
            SurfaceContainerHighest = C(0xFFE0E3EA),
            Outline             = C(0xFF73777F),
            OutlineVariant      = C(0xFFC3C6CF),
            InverseSurface      = C(0xFF2D3135),
            InverseOnSurface    = C(0xFFEEF0F6),
            InversePrimary      = C(0xFFB4C9E8),
        };

        private static readonly MusicefyColorScheme NordDark = new()
        {
            IsDark = true,
            Primary             = C(0xFFB4C9E8),
            OnPrimary           = C(0xFF1B324B),
            PrimaryContainer    = C(0xFF334963),
            OnPrimaryContainer  = C(0xFFD1E4FF),
            Secondary           = C(0xFFBAC8DB),
            OnSecondary         = C(0xFF253140),
            SecondaryContainer  = C(0xFF3B4857),
            OnSecondaryContainer= C(0xFFD6E4F7),
            Tertiary            = C(0xFFD6BEE3),
            OnTertiary          = C(0xFF3B2B47),
            TertiaryContainer   = C(0xFF52415E),
            OnTertiaryContainer = C(0xFFF2DAFF),
            Error               = C(0xFFFFB4AB),
            OnError             = C(0xFF690005),
            ErrorContainer      = C(0xFF93000A),
            OnErrorContainer    = C(0xFFFFDAD6),
            Surface             = C(0xFF101417),
            OnSurface           = C(0xFFE0E3EA),
            SurfaceVariant      = C(0xFF434750),
            OnSurfaceVariant    = C(0xFFC3C6CF),
            SurfaceContainerLowest  = C(0xFF0B0E12),
            SurfaceContainerLow     = C(0xFF181C20),
            SurfaceContainer        = C(0xFF1C2024),
            SurfaceContainerHigh    = C(0xFF272B2F),
            SurfaceContainerHighest = C(0xFF31363A),
            Outline             = C(0xFF8D919A),
            OutlineVariant      = C(0xFF434750),
            InverseSurface      = C(0xFFE0E3EA),
            InverseOnSurface    = C(0xFF2D3135),
            InversePrimary      = C(0xFF4A607B),
        };

        // ── Yin & Yang ───────────────────────────────────────────────────────

        private static readonly MusicefyColorScheme YinAndYangLight = new()
        {
            IsDark = false,
            Primary             = C(0xFF5D5D5D),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFE2E2E2),
            OnPrimaryContainer  = C(0xFF1A1A1A),
            Secondary           = C(0xFF5D5D5D),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFE2E2E2),
            OnSecondaryContainer= C(0xFF1A1A1A),
            Tertiary            = C(0xFF5D5D5D),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFE2E2E2),
            OnTertiaryContainer = C(0xFF1A1A1A),
            Error               = C(0xFFBA1A1A),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFFFDAD6),
            OnErrorContainer    = C(0xFF410002),
            Surface             = C(0xFFF9F9F9),
            OnSurface           = C(0xFF1A1A1A),
            SurfaceVariant      = C(0xFFE0E0E0),
            OnSurfaceVariant    = C(0xFF464646),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFF3F3F3),
            SurfaceContainer        = C(0xFFEEEEEE),
            SurfaceContainerHigh    = C(0xFFE8E8E8),
            SurfaceContainerHighest = C(0xFFE2E2E2),
            Outline             = C(0xFF767676),
            OutlineVariant      = C(0xFFC6C6C6),
            InverseSurface      = C(0xFF2F2F2F),
            InverseOnSurface    = C(0xFFF1F1F1),
            InversePrimary      = C(0xFFC6C6C6),
        };

        private static readonly MusicefyColorScheme YinAndYangDark = new()
        {
            IsDark = true,
            Primary             = C(0xFFC6C6C6),
            OnPrimary           = C(0xFF2F2F2F),
            PrimaryContainer    = C(0xFF454545),
            OnPrimaryContainer  = C(0xFFE2E2E2),
            Secondary           = C(0xFFC6C6C6),
            OnSecondary         = C(0xFF2F2F2F),
            SecondaryContainer  = C(0xFF454545),
            OnSecondaryContainer= C(0xFFE2E2E2),
            Tertiary            = C(0xFFC6C6C6),
            OnTertiary          = C(0xFF2F2F2F),
            TertiaryContainer   = C(0xFF454545),
            OnTertiaryContainer = C(0xFFE2E2E2),
            Error               = C(0xFFFFB4AB),
            OnError             = C(0xFF690005),
            ErrorContainer      = C(0xFF93000A),
            OnErrorContainer    = C(0xFFFFDAD6),
            Surface             = C(0xFF141414),
            OnSurface           = C(0xFFE2E2E2),
            SurfaceVariant      = C(0xFF464646),
            OnSurfaceVariant    = C(0xFFC6C6C6),
            SurfaceContainerLowest  = C(0xFF0F0F0F),
            SurfaceContainerLow     = C(0xFF1A1A1A),
            SurfaceContainer        = C(0xFF1F1F1F),
            SurfaceContainerHigh    = C(0xFF292929),
            SurfaceContainerHighest = C(0xFF343434),
            Outline             = C(0xFF909090),
            OutlineVariant      = C(0xFF464646),
            InverseSurface      = C(0xFFE2E2E2),
            InverseOnSurface    = C(0xFF2F2F2F),
            InversePrimary      = C(0xFF5D5D5D),
        };

        // ── Yotsuba ──────────────────────────────────────────────────────────

        private static readonly MusicefyColorScheme YotsubaLight = new()
        {
            IsDark = false,
            Primary             = C(0xFFC48A18),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFFFDEA6),
            OnPrimaryContainer  = C(0xFF271900),
            Secondary           = C(0xFF6B5D3F),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFF4E1BB),
            OnSecondaryContainer= C(0xFF241A04),
            Tertiary            = C(0xFF4E6544),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFD1EBCC),
            OnTertiaryContainer = C(0xFF0C2008),
            Error               = C(0xFFBA1A1A),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFFFDAD6),
            OnErrorContainer    = C(0xFF410002),
            Surface             = C(0xFFFFF8F0),
            OnSurface           = C(0xFF1E1B16),
            SurfaceVariant      = C(0xFFECE1CF),
            OnSurfaceVariant    = C(0xFF4D4639),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFF8F2E8),
            SurfaceContainer        = C(0xFFF2ECE2),
            SurfaceContainerHigh    = C(0xFFEDE6DC),
            SurfaceContainerHighest = C(0xFFE7E1D7),
            Outline             = C(0xFF7F7667),
            OutlineVariant      = C(0xFFD0C5B4),
            InverseSurface      = C(0xFF34302A),
            InverseOnSurface    = C(0xFFF6F0E5),
            InversePrimary      = C(0xFFF5BD48),
        };

        private static readonly MusicefyColorScheme YotsubaDark = new()
        {
            IsDark = true,
            Primary             = C(0xFFF5BD48),
            OnPrimary           = C(0xFF402D00),
            PrimaryContainer    = C(0xFF5C4200),
            OnPrimaryContainer  = C(0xFFFFDEA6),
            Secondary           = C(0xFFD7C5A1),
            OnSecondary         = C(0xFF3A2F15),
            SecondaryContainer  = C(0xFF52452A),
            OnSecondaryContainer= C(0xFFF4E1BB),
            Tertiary            = C(0xFFB5CFB2),
            OnTertiary          = C(0xFF223721),
            TertiaryContainer   = C(0xFF384E36),
            OnTertiaryContainer = C(0xFFD1EBCC),
            Error               = C(0xFFFFB4AB),
            OnError             = C(0xFF690005),
            ErrorContainer      = C(0xFF93000A),
            OnErrorContainer    = C(0xFFFFDAD6),
            Surface             = C(0xFF16130E),
            OnSurface           = C(0xFFE7E1D7),
            SurfaceVariant      = C(0xFF4D4639),
            OnSurfaceVariant    = C(0xFFD0C5B4),
            SurfaceContainerLowest  = C(0xFF100D09),
            SurfaceContainerLow     = C(0xFF1E1B16),
            SurfaceContainer        = C(0xFF221F1A),
            SurfaceContainerHigh    = C(0xFF2D2A24),
            SurfaceContainerHighest = C(0xFF38342F),
            Outline             = C(0xFF99907F),
            OutlineVariant      = C(0xFF4D4639),
            InverseSurface      = C(0xFFE7E1D7),
            InverseOnSurface    = C(0xFF34302A),
            InversePrimary      = C(0xFFC48A18),
        };

        // ── Monochrome ───────────────────────────────────────────────────────

        private static readonly MusicefyColorScheme MonochromeLight = new()
        {
            IsDark = false,
            Primary             = C(0xFF616161),
            OnPrimary           = C(0xFFFFFFFF),
            PrimaryContainer    = C(0xFFE6E6E6),
            OnPrimaryContainer  = C(0xFF1E1E1E),
            Secondary           = C(0xFF5E5E5E),
            OnSecondary         = C(0xFFFFFFFF),
            SecondaryContainer  = C(0xFFE4E4E4),
            OnSecondaryContainer= C(0xFF1B1B1B),
            Tertiary            = C(0xFF5E5E5E),
            OnTertiary          = C(0xFFFFFFFF),
            TertiaryContainer   = C(0xFFE4E4E4),
            OnTertiaryContainer = C(0xFF1B1B1B),
            Error               = C(0xFFBA1A1A),
            OnError             = C(0xFFFFFFFF),
            ErrorContainer      = C(0xFFFFDAD6),
            OnErrorContainer    = C(0xFF410002),
            Surface             = C(0xFFF9F9F9),
            OnSurface           = C(0xFF1A1A1A),
            SurfaceVariant      = C(0xFFEBEBEB),
            OnSurfaceVariant    = C(0xFF4C4C4C),
            SurfaceContainerLowest  = C(0xFFFFFFFF),
            SurfaceContainerLow     = C(0xFFF3F3F3),
            SurfaceContainer        = C(0xFFEEEEEE),
            SurfaceContainerHigh    = C(0xFFE8E8E8),
            SurfaceContainerHighest = C(0xFFE2E2E2),
            Outline             = C(0xFF7C7C7C),
            OutlineVariant      = C(0xFFCFCFCF),
            InverseSurface      = C(0xFF2F2F2F),
            InverseOnSurface    = C(0xFFF1F1F1),
            InversePrimary      = C(0xFFCACACA),
        };

        private static readonly MusicefyColorScheme MonochromeDark = new()
        {
            IsDark = true,
            Primary             = C(0xFFCACACA),
            OnPrimary           = C(0xFF333333),
            PrimaryContainer    = C(0xFF4A4A4A),
            OnPrimaryContainer  = C(0xFFE6E6E6),
            Secondary           = C(0xFFC8C8C8),
            OnSecondary         = C(0xFF303030),
            SecondaryContainer  = C(0xFF474747),
            OnSecondaryContainer= C(0xFFE4E4E4),
            Tertiary            = C(0xFFC8C8C8),
            OnTertiary          = C(0xFF303030),
            TertiaryContainer   = C(0xFF474747),
            OnTertiaryContainer = C(0xFFE4E4E4),
            Error               = C(0xFFFFB4AB),
            OnError             = C(0xFF690005),
            ErrorContainer      = C(0xFF93000A),
            OnErrorContainer    = C(0xFFFFDAD6),
            Surface             = C(0xFF141414),
            OnSurface           = C(0xFFE2E2E2),
            SurfaceVariant      = C(0xFF4C4C4C),
            OnSurfaceVariant    = C(0xFFCFCFCF),
            SurfaceContainerLowest  = C(0xFF0F0F0F),
            SurfaceContainerLow     = C(0xFF1C1C1C),
            SurfaceContainer        = C(0xFF212121),
            SurfaceContainerHigh    = C(0xFF2B2B2B),
            SurfaceContainerHighest = C(0xFF363636),
            Outline             = C(0xFF969696),
            OutlineVariant      = C(0xFF4C4C4C),
            InverseSurface      = C(0xFFE2E2E2),
            InverseOnSurface    = C(0xFF2F2F2F),
            InversePrimary      = C(0xFF616161),
        };
    }
}
