//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated as a safe fallback for CI builds.
//     If you maintain a Resources.resx file, the build will normally regenerate
//     this designer file from the .resx. This fallback prevents CS2001 when
//     the generated file is not present during temporary assembly compilation.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Globalization;
using System.Resources;

namespace Musicefy.Properties
{
    /// <summary>
    ///   Strongly-typed resource class for fallback resources.
    /// </summary>
    internal static class Resources
    {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    resourceMan = new ResourceManager("Musicefy.Properties.Resources", typeof(Resources).Assembly);
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture for resource lookups.
        /// </summary>
        internal static CultureInfo Culture
        {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        // Example placeholder property. Add real resource properties if you have entries in Resources.resx.
        internal static string AppTitle
        {
            get
            {
                return ResourceManager.GetString("AppTitle", resourceCulture) ?? "Musicefy";
            }
        }
    }
}
