jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.2.0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Restore NuGet packages
        shell: pwsh
        run: msbuild Musicefy.sln /t:Restore

      - name: Clean bin and obj folders
        shell: pwsh
        run: |
          Write-Host "Cleaning bin and obj folders..."
          Get-ChildItem -Path . -Include bin,obj -Recurse -Force | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue

      - name: Rebuild solution
        shell: pwsh
        run: msbuild Musicefy.sln /t:Rebuild /p:Configuration=Release /p:Platform="Any CPU"
